apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:yv8bz5+6m1ZDmi0H,iv:ELJztP6d7oRxq6xeSomOvBBHqtqKfEgbdsyqYYdDWkQ=,tag:9fZ6q0njuzMHcltHOaDmLg==,type:str]
    password: ENC[AES256_GCM,data:iFUZvb7IMN3NWs98,iv:fFkfV6+bjTCt37MdR1OicHcovApUoItVMC/xVZAd4xc=,tag:iYEhQPh/4NHmUf2vEQzwng==,type:str]
sops:
    age:
        - recipient: age1qdh2vdjjxhxlnlrmpgeps8wueut49ccw0fsxyslf8lsvecv0psrs8ph53k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIL3dsQlNpeHQ3ck1EbDZ4
            RnM5TUhPaFBLNlIrYkNQQ0pZZzVvd2E2VlhzCjU0b0p6NHYxM1ZaY2VBeWhVa2ZZ
            Rm1UUVdDWW90TkwwT0E3TU9sYW91bzAKLS0tIFZnRDNhY25IWjZqZlJhNHpKUmJS
            YUZJVGhoSU1XVHYwUVlmOTJIRnhrWm8KLfvS3gXKHn04FY6LQOs4lqfah1gFYMAZ
            c2psAdFtbf2KEvNXSZC86PdoB1taJGaUXE8MBHVyNVPNyDxkZ/1Kqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-06T13:45:36Z"
    mac: ENC[AES256_GCM,data:stvRGVSlKLkcIJRViL6leNfdM6wiwVQQMXc3oqQI7yN3DtWTnDUkujTZNp8+YyhfBNGN3+rZijnRNu5L105wU/YkpMwXiFTDG0XiE6wcu/VgksYHyE9zG2rWkrtKNbUQBdYvuVCtPxaswZumHK53NcH7WJdFnrYgJ9tlAc8IOQQ=,iv:Gu3qAFo/T7Tne3aIBGbYK0XQ/KBWyPg62AHcZpOM3ys=,tag:XsSEhdG5gZSs+lm9r57J4g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
