apiVersion: v1
kind: Secret
metadata:
    name: mysecret
    namespace: ksops-test
type: Opaque
data:
    username: ENC[AES256_GCM,data:m5C0ScW7u4coWXxRICBCRA==,iv:cq47iOYThcISRAA0C294dENTEi/iYZxVaDTWDuO8RAI=,tag:xxagsJEdpMRgLdrgpebECQ==,type:str]
    password: ENC[AES256_GCM,data:bL+kElr/gBZG8qjewnK6Xg==,iv:Y0k5r0Q/9N33S+7Z1e6ZDQLG1qUG22S1zBpZ9FSvJQA=,tag:7LF01ti3D4EhOeWMptqQ9A==,type:str]
sops:
    age:
        - recipient: age1qdh2vdjjxhxlnlrmpgeps8wueut49ccw0fsxyslf8lsvecv0psrs8ph53k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVkxiODRoYTdNSzNWMXRE
            VXNHWDFFTGJaaG45bUNmSSswWUJ1OGZGS2tBCkRPQ0tJak42T3pkQ1ZiQTdMTW9C
            alZDUkNTOHZDVkd4S09iZXZtd08vaDgKLS0tIDk0S3BsZEN6QjJneVh4bVQ0Rzlw
            MVZ0emt5SERKa09sTTd5cDl3bVdHTFkKjyET7aohqpMRjprjaF/EvgHOtL30t/Qz
            4WUQVFAMrTEOr6ZZd9JL4952M5wHXyl3mruTQlJg7lxQb9xN1Uk/1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-06T13:58:28Z"
    mac: ENC[AES256_GCM,data:8eSl3bHTFCgQSgrTIaJUxjDa88LYuHSXPPyQvDtaCazXBtZVZqIv8RgbRROHUJSvSgN1QdYtRKnzVeJS/vu83mcrBEgo1EzVmUtw9QEMDfbF68A70CVtyJ/Nqt0mKaQapZjtu00xFY9Aq5nxC30SHMJaRwa7M8WBbFerRdrF8O8=,iv:l14yk//AV0wAZ91LUGDF9YN2dR7Hhy9PMbR14S40iy0=,tag:dUyhLOofuKOs/xjBAyMYhw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
