apiVersion: v1
kind: Secret
metadata:
    name: mysecret
    namespace: ksops-test
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:hMXNizLLyLc=,iv:g7iZO/SBwicUX7jC6doz5yZ/mtd30aJgMvi/1kvcFbg=,tag:VhQNQVnW25ZwVlMjT7GXQw==,type:str]
    password: ENC[AES256_GCM,data:0ooZqC1eiqY=,iv:9BCpO8yNd29bxvUqFXeZ0Ng3mWln1CfNBZnho5BPGWE=,tag:yH4uMeOM9X9wL5QoHou3Cw==,type:str]
sops:
    azure_kv:
        - vault_url: https://argocd-sops123123.vault.azure.net
          name: argo-sops-key
          version: 19ece3a94a474430b9db03bff89dd15f
          created_at: "2025-05-06T14:09:10Z"
          enc: M9RfPHcieK3wTXDjcfq9X3a-ck1NLDG4vTqHveSwDRxf22kPvmzegHB2Twjd4aZBFYsK_kQ1hOsy1cAtbZnjyj-oc6AHWrG_-22XMf9l7daVcqyu-CT-aZUa-tzKH9jsnZgDUUCCKtR3JtUfBpaJHzzHYCuRn1JCK6YaQnzBFXeJ8x6zGq6NfoHKFzbsidr6O42yBPpbRYlKb3g5K5T2EWqQOBOK-MDXMckVAbzP3csQtrUNiumobkBRp5Q7KInZx2Ua-DtKLoeC-EP5BkKtOfF75-RlArV_UhhAU7GTFR2u0ZYWCq0DDT1S5epNqpTj2Lmdz9kSJegiilVbShGw4w
    lastmodified: "2025-05-06T14:09:11Z"
    mac: ENC[AES256_GCM,data:/18WkFiA1UpLXIfzX4C1klWek0XATpEFioB/g+/+CIYZ99K/lOVUwGGz5LVRFUF3mRY3nyX1wepRVZ48thcOcTl2ZHAJRBqmQSRirymc1t0ZVb+NAvM62kO0ELUxANQgWbmd0K5V1MnAT+EdhoD8LHXlCm/lxH+CadvGSLJaOsI=,iv:9pMNaRZx67cfGWy2YlYyK71luOd3FOHQl2viDK2u+wI=,tag:Hs7cl2+eHhyu5pAGxzANSw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
